version: '3.7'

services:
  productapp-mongodb:
    container_name: app_mongodb
    image: mongo:4.0
    environment:
      TZ: America/Sao_Paulo
    restart: always
    volumes:
      - productapp_db
    networks:
      - productapp_network

  productapp:
    container_name: app_php
    build: ./docker/php
    volumes:
      - ./:/var/www
    networks:
      - productapp_network

  productapp-nginx:
    container_name: app_nginx
    build: ./docker/nginx
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
    networks:
      - productapp_network

volumes:
  productapp_db:

networks:
  productapp_network:
